services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=apigateway,lambda,dynamodb,sqs,s3,ssm
      - DEFAULT_REGION=sa-east-1
      - EAGER_SERVICE_LOADING=1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
