org: wppbussnisdias

service: ajudo-assistant-ia
frameworkVersion: "4"

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs24.x
  memorySize: 128

package:
  indiviadually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    external:
      - '@aws-sdk/*'

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: GET
