org: wppbussnisdias

service: ajudo-assistant-ia
frameworkVersion: "4"

useDotenv: true

plugins: ${file(sls/config/plugins.yml)}

custom: ${file(sls/config/custom.yml)}

provider: ${file(sls/config/provider.yml)}

package: ${file(sls/config/package.yml)}

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  whatsappWebhook: ${file(sls/functions/whatsappWebhook.yml)}

resources: ${file(sls/resources/MainTable.yml)}
