export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',
  AI_PARSE_FAILURE = 'AI_PARSE_FAILURE',
  INVALID_MEDIA_COUNT = 'INVALID_MEDIA_COUNT',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
}
